In [2]:
import gym

In [2]:
env = gym.make('MountainCarContinuous-v0')

In [3]:
print(env.action_space)
print(env.action_space.high)
print(env.action_space.low)
print(env.observation_space)
print(env.observation_space.high)
print(env.observation_space.low)

Box(1,)
[1.]
[-1.]
Box(2,)
[0.6  0.07]
[-1.2  -0.07]


In [4]:
env.render()

True

In [ ]:
import mujoco_py

In [40]:
state = env.reset()
env.render()

True

In [41]:
print(state)

[-0.57964144  0.        ]


In [35]:
init = env.env.state

In [44]:
for i in range(100):
    state = env.step([1])
    print(state)
    env.render()

(array([-0.49342415,  0.01596824]), -0.1, False, {})
(array([-0.47618191,  0.01724224]), -0.1, False, {})
(array([-0.4577941 ,  0.01838781]), -0.1, False, {})
(array([-0.43839663,  0.01939747]), -0.1, False, {})
(array([-0.41813124,  0.02026539]), -0.1, False, {})
(array([-0.39714372,  0.02098752]), -0.1, False, {})
(array([-0.37558202,  0.02156169]), -0.1, False, {})
(array([-0.35359433,  0.02198769]), -0.1, False, {})
(array([-0.33132712,  0.02226722]), -0.1, False, {})
(array([-0.30892329,  0.02240383]), -0.1, False, {})
(array([-0.28652051,  0.02240278]), -0.1, False, {})
(array([-0.26424966,  0.02227085]), -0.1, False, {})
(array([-0.24223354,  0.02201613]), -0.1, False, {})
(array([-0.22058584,  0.0216477 ]), -0.1, False, {})
(array([-0.19941042,  0.02117542]), -0.1, False, {})
(array([-0.17880084,  0.02060958]), -0.1, False, {})
(array([-0.15884014,  0.0199607 ]), -0.1, False, {})
(array([-0.13960092,  0.01923921]), -0.1, False, {})
(array([-0.12114565,  0.01845527]), -0.1, Fals

In [39]:
env.env.state = init
env.render()

True

In [37]:
print(init)

[-0.55226439  0.        ]


In [29]:
for i in range(10):
    env.step([1])
env.render()

True

In [19]:
import gym
import torch
import torch.nn as nn

In [65]:
class ValueNet(nn.Module):
    def __init__(self, input_dim, hidden, output_dim):
        super(ValueNet, self).__init__()
        
        self.model = nn.Sequential(
            nn.Linear(input_dim, hidden),
            nn.Tanh(),
            nn.Linear(hidden, hidden),
            nn.Tanh(),
            nn.Linear(hidden, output_dim),
        )
    
    def forward(self, x):
        return self.model(x)

In [66]:
net = ValueNet(3, 16, 1)

In [166]:
print(net)

ValueNet(
  (model): Sequential(
    (0): Linear(in_features=3, out_features=16, bias=True)
    (1): Tanh()
    (2): Linear(in_features=16, out_features=16, bias=True)
    (3): Tanh()
    (4): Linear(in_features=16, out_features=1, bias=True)
  )
)


In [167]:
params = list(net.parameters())
print(len(params))
print(params[0].size())
# print(params)

6
torch.Size([16, 3])


In [168]:
input = torch.randn(3)
out = net(input)
print(out)

tensor([-0.3720], grad_fn=<AddBackward0>)


In [59]:
ENV_NAME = "Pendulum-v0"

In [60]:
env = gym.make(ENV_NAME)

In [68]:
print(env.observation_space.shape[0])
print(env.action_space.shape[0])

3
1


In [69]:
HIDDEN_LAYER = 16

In [67]:
net = ValueNet(env.observation_space.shape[0], HIDDEN_LAYER, env.action_space.shape[0])

NameError: name 'HIDDEN_LAYER' is not defined

In [169]:
print(net)

ValueNet(
  (model): Sequential(
    (0): Linear(in_features=3, out_features=16, bias=True)
    (1): Tanh()
    (2): Linear(in_features=16, out_features=16, bias=True)
    (3): Tanh()
    (4): Linear(in_features=16, out_features=1, bias=True)
  )
)


In [72]:
loss_func = nn.L1Loss()

In [69]:
optimizer = torch.optim.Adam(net.parameters())

In [102]:
data_in = torch.tensor([[1.0,3.0,4.0],[2.0,3.0,4.0]])

In [90]:
data_in = torch.randn(1,3)

In [103]:
pred = net(data_in)

In [92]:
print(data_in)

tensor([[-0.8643,  1.0641,  2.4163]])


In [104]:
print(data_in)

tensor([[1., 3., 4.],
        [2., 3., 4.]])


In [105]:
print(pred)

tensor([[0.1146],
        [0.1201]], grad_fn=<TanhBackward>)


In [106]:
y = torch.tensor([[1.0], [2.0]])

In [108]:
l = loss(pred, y)

In [111]:
optimizer.zero_grad()

In [113]:
l.backward()

In [114]:
optimizer.step()

In [170]:
print(net)

ValueNet(
  (model): Sequential(
    (0): Linear(in_features=3, out_features=16, bias=True)
    (1): Tanh()
    (2): Linear(in_features=16, out_features=16, bias=True)
    (3): Tanh()
    (4): Linear(in_features=16, out_features=1, bias=True)
  )
)


In [73]:
for t in range(-100,100):
    for _ in range(100):
        i = float(t)
        data_in = torch.tensor([[float(i),float(i),float(i)]])

        optimizer.zero_grad()
        pred = net(data_in)
        
        target = torch.tensor([[float(i)]])
        print("{}\t{}\t{}".format(t, _, target))
        loss = loss_func(pred, target)
#         print(t, loss.item())

        loss.backward()
        optimizer.step()

-100	0	tensor([[-100.]])
-100	1	tensor([[-100.]])
-100	2	tensor([[-100.]])
-100	3	tensor([[-100.]])
-100	4	tensor([[-100.]])
-100	5	tensor([[-100.]])
-100	6	tensor([[-100.]])
-100	7	tensor([[-100.]])
-100	8	tensor([[-100.]])
-100	9	tensor([[-100.]])
-100	10	tensor([[-100.]])
-100	11	tensor([[-100.]])
-100	12	tensor([[-100.]])
-100	13	tensor([[-100.]])
-100	14	tensor([[-100.]])
-100	15	tensor([[-100.]])
-100	16	tensor([[-100.]])
-100	17	tensor([[-100.]])
-100	18	tensor([[-100.]])
-100	19	tensor([[-100.]])
-100	20	tensor([[-100.]])
-100	21	tensor([[-100.]])
-100	22	tensor([[-100.]])
-100	23	tensor([[-100.]])
-100	24	tensor([[-100.]])
-100	25	tensor([[-100.]])
-100	26	tensor([[-100.]])
-100	27	tensor([[-100.]])
-100	28	tensor([[-100.]])
-100	29	tensor([[-100.]])
-100	30	tensor([[-100.]])
-100	31	tensor([[-100.]])
-100	32	tensor([[-100.]])
-100	33	tensor([[-100.]])
-100	34	tensor([[-100.]])
-100	35	tensor([[-100.]])
-100	36	tensor([[-100.]])
-100	37	tensor([[-100.]])
-100	38	tensor([[-100.

-95	3	tensor([[-95.]])
-95	4	tensor([[-95.]])
-95	5	tensor([[-95.]])
-95	6	tensor([[-95.]])
-95	7	tensor([[-95.]])
-95	8	tensor([[-95.]])
-95	9	tensor([[-95.]])
-95	10	tensor([[-95.]])
-95	11	tensor([[-95.]])
-95	12	tensor([[-95.]])
-95	13	tensor([[-95.]])
-95	14	tensor([[-95.]])
-95	15	tensor([[-95.]])
-95	16	tensor([[-95.]])
-95	17	tensor([[-95.]])
-95	18	tensor([[-95.]])
-95	19	tensor([[-95.]])
-95	20	tensor([[-95.]])
-95	21	tensor([[-95.]])
-95	22	tensor([[-95.]])
-95	23	tensor([[-95.]])
-95	24	tensor([[-95.]])
-95	25	tensor([[-95.]])
-95	26	tensor([[-95.]])
-95	27	tensor([[-95.]])
-95	28	tensor([[-95.]])
-95	29	tensor([[-95.]])
-95	30	tensor([[-95.]])
-95	31	tensor([[-95.]])
-95	32	tensor([[-95.]])
-95	33	tensor([[-95.]])
-95	34	tensor([[-95.]])
-95	35	tensor([[-95.]])
-95	36	tensor([[-95.]])
-95	37	tensor([[-95.]])
-95	38	tensor([[-95.]])
-95	39	tensor([[-95.]])
-95	40	tensor([[-95.]])
-95	41	tensor([[-95.]])
-95	42	tensor([[-95.]])
-95	43	tensor([[-95.]])
-95	44	tensor([[-95.]])

-92	51	tensor([[-92.]])
-92	52	tensor([[-92.]])
-92	53	tensor([[-92.]])
-92	54	tensor([[-92.]])
-92	55	tensor([[-92.]])
-92	56	tensor([[-92.]])
-92	57	tensor([[-92.]])
-92	58	tensor([[-92.]])
-92	59	tensor([[-92.]])
-92	60	tensor([[-92.]])
-92	61	tensor([[-92.]])
-92	62	tensor([[-92.]])
-92	63	tensor([[-92.]])
-92	64	tensor([[-92.]])
-92	65	tensor([[-92.]])
-92	66	tensor([[-92.]])
-92	67	tensor([[-92.]])
-92	68	tensor([[-92.]])
-92	69	tensor([[-92.]])
-92	70	tensor([[-92.]])
-92	71	tensor([[-92.]])
-92	72	tensor([[-92.]])
-92	73	tensor([[-92.]])
-92	74	tensor([[-92.]])
-92	75	tensor([[-92.]])
-92	76	tensor([[-92.]])
-92	77	tensor([[-92.]])
-92	78	tensor([[-92.]])
-92	79	tensor([[-92.]])
-92	80	tensor([[-92.]])
-92	81	tensor([[-92.]])
-92	82	tensor([[-92.]])
-92	83	tensor([[-92.]])
-92	84	tensor([[-92.]])
-92	85	tensor([[-92.]])
-92	86	tensor([[-92.]])
-92	87	tensor([[-92.]])
-92	88	tensor([[-92.]])
-92	89	tensor([[-92.]])
-92	90	tensor([[-92.]])
-92	91	tensor([[-92.]])
-92	92	tensor([[

-89	95	tensor([[-89.]])
-89	96	tensor([[-89.]])
-89	97	tensor([[-89.]])
-89	98	tensor([[-89.]])
-89	99	tensor([[-89.]])
-88	0	tensor([[-88.]])
-88	1	tensor([[-88.]])
-88	2	tensor([[-88.]])
-88	3	tensor([[-88.]])
-88	4	tensor([[-88.]])
-88	5	tensor([[-88.]])
-88	6	tensor([[-88.]])
-88	7	tensor([[-88.]])
-88	8	tensor([[-88.]])
-88	9	tensor([[-88.]])
-88	10	tensor([[-88.]])
-88	11	tensor([[-88.]])
-88	12	tensor([[-88.]])
-88	13	tensor([[-88.]])
-88	14	tensor([[-88.]])
-88	15	tensor([[-88.]])
-88	16	tensor([[-88.]])
-88	17	tensor([[-88.]])
-88	18	tensor([[-88.]])
-88	19	tensor([[-88.]])
-88	20	tensor([[-88.]])
-88	21	tensor([[-88.]])
-88	22	tensor([[-88.]])
-88	23	tensor([[-88.]])
-88	24	tensor([[-88.]])
-88	25	tensor([[-88.]])
-88	26	tensor([[-88.]])
-88	27	tensor([[-88.]])
-88	28	tensor([[-88.]])
-88	29	tensor([[-88.]])
-88	30	tensor([[-88.]])
-88	31	tensor([[-88.]])
-88	32	tensor([[-88.]])
-88	33	tensor([[-88.]])
-88	34	tensor([[-88.]])
-88	35	tensor([[-88.]])
-88	36	tensor([[-88.]])
-8

-85	67	tensor([[-85.]])
-85	68	tensor([[-85.]])
-85	69	tensor([[-85.]])
-85	70	tensor([[-85.]])
-85	71	tensor([[-85.]])
-85	72	tensor([[-85.]])
-85	73	tensor([[-85.]])
-85	74	tensor([[-85.]])
-85	75	tensor([[-85.]])
-85	76	tensor([[-85.]])
-85	77	tensor([[-85.]])
-85	78	tensor([[-85.]])
-85	79	tensor([[-85.]])
-85	80	tensor([[-85.]])
-85	81	tensor([[-85.]])
-85	82	tensor([[-85.]])
-85	83	tensor([[-85.]])
-85	84	tensor([[-85.]])
-85	85	tensor([[-85.]])
-85	86	tensor([[-85.]])
-85	87	tensor([[-85.]])
-85	88	tensor([[-85.]])
-85	89	tensor([[-85.]])
-85	90	tensor([[-85.]])
-85	91	tensor([[-85.]])
-85	92	tensor([[-85.]])
-85	93	tensor([[-85.]])
-85	94	tensor([[-85.]])
-85	95	tensor([[-85.]])
-85	96	tensor([[-85.]])
-85	97	tensor([[-85.]])
-85	98	tensor([[-85.]])
-85	99	tensor([[-85.]])
-84	0	tensor([[-84.]])
-84	1	tensor([[-84.]])
-84	2	tensor([[-84.]])
-84	3	tensor([[-84.]])
-84	4	tensor([[-84.]])
-84	5	tensor([[-84.]])
-84	6	tensor([[-84.]])
-84	7	tensor([[-84.]])
-84	8	tensor([[-84.]])
-

KeyboardInterrupt: 

In [180]:
num = 99.0
print(net(torch.tensor([[num,num,num]])))

tensor([[0.0118]], grad_fn=<AddmmBackward>)


In [189]:
data_in = torch.tensor([[-100.0, -100.0, -100.0]])
for i in range(-99, 100):
    d = float(i)
    data_in = torch.cat((data_in, torch.tensor([[d,d,d]])))

In [190]:
targets = torch.tensor([[-100.0]])
for i in range(-99, 100):
    d = float(i)
    targets = torch.cat((targets, torch.tensor([[d]])))

In [197]:
ValueNet(env.observation_space.shape[0], HIDDEN_LAYER, env.action_space.shape[0])

ValueNet(
  (model): Sequential(
    (0): Linear(in_features=3, out_features=16, bias=True)
    (1): Tanh()
    (2): Linear(in_features=16, out_features=16, bias=True)
    (3): Tanh()
    (4): Linear(in_features=16, out_features=1, bias=True)
  )
)

In [209]:
loss_func = nn.L1Loss()

In [210]:
optimizer = torch.optim.Adam(net.parameters())

In [62]:
for _ in range(10000):
#     i = float(t)
#     data_in = torch.tensor([[float(i),float(i),float(i)]])

    optimizer.zero_grad()
    preds = net(data_in)
#     print("{}\t{}\t{}".format(_, targets))
#     target = torch.tensor([[float(i)]])
    loss = loss_func(preds, targets)
    print(loss)
#         print(t, loss.item())

    loss.backward()
    optimizer.step()

NameError: name 'optimizer' is not defined

In [202]:
print(data_in.shape)
print(targets.shape)

torch.Size([200, 3])
torch.Size([200, 1])


In [218]:
num = -33.0
print(net(torch.tensor([[num,num,num]])))

tensor([[-32.7767]], grad_fn=<AddmmBackward>)


In [1]:
import gym
import torch
import torch.nn as nn
import numpy as np
from scipy.special import softmax

In [2]:
class ValueNet(nn.Module):
    def __init__(self, input_dim, hidden, output_dim):
        super(ValueNet, self).__init__()
        
        self.model = nn.Sequential(
            nn.Linear(input_dim, hidden),
            nn.Tanh(),
            nn.Linear(hidden, hidden),
            nn.Tanh(),
            nn.Linear(hidden, output_dim),
        )
    
    def forward(self, x):
        return self.model(x)

In [3]:
class POLO(object):
    def __init__(self, K, T, lambda_, noise_mu, noise_sigma, U, u_init, memory_size, 
                 observation_space, action_space, state_space, net_hidden_layers, num_nets, gamma, 
                 state_samples, gradient_steps, noise_gaussian=True):
        self.memory_size = memory_size
        self.obs_mem = np.zeros((self.memory_size, observation_space))
        self.state_mem = np.zeros((self.memory_size, state_space))
        
        self.K = K  # N_SAMPLES
        self.T = T  # TIMESTEPS
        self.lambda_ = lambda_
        self.noise_mu = noise_mu
        self.noise_sigma = noise_sigma
        self.U = U
        self.u_init = u_init
        self.reward_total = np.zeros(shape=(self.K))
        self.gamma = gamma
        self.state_samples = state_samples
        self.gradient_steps = gradient_steps


        if noise_gaussian:
            self.noise = np.random.normal(loc=self.noise_mu, scale=self.noise_sigma, size=(self.K, self.T))
        else:
            self.noise = np.full(shape=(self.K, self.T), fill_value=0.9)
        
        self.num_nets = num_nets
        
        self._build_value_nets(observation_space, net_hidden_layers, action_space)

    
    def _build_value_nets(self, input_dim, hidden, output_dim):
        self.value_nets = []
        self.loss_funcs = []
        self.optimizers = []
        
        for i in range(self.num_nets):
            self.value_nets.append(ValueNet(input_dim, hidden, output_dim))
            self.loss_funcs.append(nn.MSELoss())
            self.optimizers.append(torch.optim.Adam(self.value_nets[-1].parameters()))
            
        
    def get_aggregated_value(self, s):
        values = []
        for net in self.value_nets:
            values.append(net(torch.tensor(s, dtype=torch.float)).item())
            
        values = np.array(values)
        weights = softmax(values)
        weighted_values = values * weights

        return sum(weighted_values)
        
    def learn(self, env):
        init_state = env.env.state
        for _ in range(self.gradient_steps):
            idx = np.random.choice(np.min([self.memory_counter, self.memory_size]), size=self.state_samples, replace=False)

            sampled_states = self.state_mem[idx,:]

            sampled_obs = self.obs_mem[idx,:]



            targets = x = [None for i in range(self.num_nets)]


            for s_state, o in zip(sampled_states, sampled_obs):
                discount = 1
                total_reward = 0

                max_rewards = [float('-inf') for _ in range(self.num_nets)]

                for k in range(self.K):
                    env.env.state = s_state
                    for t in range(self.T):
                        perturbed_action_t = self.U[t] + self.noise[k, t]

                        s, reward, _, _ = env.step([perturbed_action_t])

                        total_reward += discount * reward
                        discount *= self.gamma

                    for i in range(self.num_nets):
                        net = self.value_nets[i]
                        reward_for_net = torch.tensor(total_reward, dtype=torch.float) + net(torch.tensor(s, dtype=torch.float))
                        if reward_for_net > max_rewards[i]:
                            max_rewards[i] = reward_for_net



                for i in range(self.num_nets):
                    net = self.value_nets[i]
                    loss_func = self.loss_funcs[i]
                    optimizer = self.optimizers[i]

                    target = max_rewards[i]

                    if targets[i] is None:
                        targets[i] = torch.tensor([[target]], dtype=torch.float)
                    else:
                        targets[i] = torch.cat((targets[i], torch.tensor([[target]], dtype=torch.float)))

        env.env.state = init_state
        

        for i in range(self.num_nets):
            net = self.value_nets[i]
            loss_func = self.loss_funcs[i]
            optimizer = self.optimizers[i]
            
            optimizer.zero_grad()
            
            preds = net(torch.tensor(sampled_obs, dtype=torch.float))
            
            loss = loss_func(preds, targets[i])
            
            loss.backward()
            optimizer.step()

    
    def _compute_total_reward(self, k, env):
        discount = 1
        for t in range(self.T):
            perturbed_action_t = self.U[t] + self.noise[k, t]
            s, reward, _, _ = env.step([perturbed_action_t])
            self.reward_total[k] += discount * reward
            discount *= self.gamma
        self.reward_total[k] += discount * self.get_aggregated_value(s)
    
    def _ensure_non_zero(self, reward, beta, factor):
        return np.exp(-factor * (beta - reward))
    
    def choose_action(self, env):
        init = env.env.state
        for k in range(self.K):
            self._compute_total_reward(k, env)
            env.env.state = init
        
        beta = np.max(self.reward_total)  # maximize reward of all trajectories
        reward_total_non_zero = self._ensure_non_zero(reward=self.reward_total, beta=beta, factor=1/self.lambda_)

        eta = np.sum(reward_total_non_zero)
        omega = 1/eta * reward_total_non_zero

        self.U += [np.sum(omega * self.noise[:, t]) for t in range(self.T)]
        
        
        env.env.state = init
        action = self.U[0]
        
        self.U = np.roll(self.U, -1)  # shift all elements to the left
        self.U[-1] = self.u_init  #
        self.reward_total[:] = 0
        
        
        return action
    
    
    def store_state(self, obs, state):
        if not hasattr(self, 'memory_counter'):
            self.memory_counter = 0

        # replace the old memory with new memory
        index = self.memory_counter % self.memory_size
        self.obs_mem[index] = np.array(obs)
        self.state_mem[index] = np.array(state)

        self.memory_counter += 1
    

In [ ]:
ENV_NAME = "Pendulum-v0"
TIMESTEPS = 13 # T
N_SAMPLES = 100  # K

env = gym.make(ENV_NAME)
ACTION_LOW = env.action_space.low[0]
ACTION_HIGH = env.action_space.high[0]

noise_mu = 0
noise_sigma = 0.3
lambda_ = 1

Z = 16

U = np.random.uniform(low=ACTION_LOW, high=ACTION_HIGH, size=TIMESTEPS)

s = env.reset()

polo = POLO(K=N_SAMPLES, T=TIMESTEPS, U=U, lambda_=lambda_, noise_mu=noise_mu, 
            noise_sigma=noise_sigma, u_init=0, memory_size=512, 
            observation_space=env.observation_space.shape[0], action_space=env.action_space.shape[0], 
            state_space=len(env.env.state),
            net_hidden_layers=16, num_nets=6, gamma=0.99, state_samples=8, gradient_steps=16, noise_gaussian=True)


env.render()
polo.store_state(s, env.env.state)

for t in range(10000):
    a = polo.choose_action(env)
    s, r, _, _ = env.step([a])
    print("action taken: {:.2f} reward received: {:.2f}".format(a, r))
    env.render()
    polo.store_state(s, env.env.state)
    
    if t != 0 and t % Z == 0:
        polo.learn(env)


action taken: -0.68 reward received: -1.09
action taken: 0.21 reward received: -0.98
action taken: -0.73 reward received: -1.00
action taken: -0.44 reward received: -1.13
action taken: 1.07 reward received: -1.40
action taken: 1.07 reward received: -1.95
action taken: -1.52 reward received: -2.79
action taken: -2.10 reward received: -3.65
action taken: 1.80 reward received: -4.64
action taken: 1.37 reward received: -6.49
action taken: -1.83 reward received: -8.72
action taken: -0.86 reward received: -10.59
action taken: 0.15 reward received: -12.70
action taken: -0.12 reward received: -13.60
action taken: -0.07 reward received: -11.59
action taken: 0.01 reward received: -9.58
action taken: 0.16 reward received: -7.69
action taken: 0.28 reward received: -6.02
action taken: 0.41 reward received: -4.61
action taken: 0.53 reward received: -3.48
action taken: 0.65 reward received: -2.61
action taken: 0.77 reward received: -1.97
action taken: 0.88 reward received: -1.51
action taken: 0.98 re

action taken: -0.88 reward received: -1.87
action taken: -0.76 reward received: -2.28
action taken: -0.65 reward received: -2.89
action taken: -0.55 reward received: -3.73
action taken: -0.43 reward received: -4.84
action taken: -0.37 reward received: -6.22
action taken: -0.27 reward received: -7.87
action taken: -0.14 reward received: -9.74
action taken: -0.09 reward received: -11.75
action taken: -0.03 reward received: -13.16
action taken: 0.05 reward received: -11.36
action taken: 0.16 reward received: -9.55
action taken: 0.28 reward received: -7.83
action taken: 0.40 reward received: -6.28
action taken: 0.53 reward received: -4.94
action taken: 0.65 reward received: -3.85
action taken: 0.76 reward received: -3.00
action taken: 0.87 reward received: -2.37
action taken: 0.98 reward received: -1.93
action taken: 1.07 reward received: -1.66
action taken: 1.11 reward received: -1.52
action taken: 1.11 reward received: -1.51
action taken: 1.10 reward received: -1.62
action taken: 1.01 re